<?php
require('fpdf/fpdf.php');

include('../texas/list_register.php');

$jsonData = json_decode($jsonString);

foreach ($jsonData as $item) {
    $id_vehicle = $item->id_vehicle;
    $vin_vehicle = $item->vin_vehicle;
    $seller = $item->seller;
    $deler_number=$item->deler_number;
    $body_style = $item->body_style;
    $major_color = $item->major_color;
    $minor_color = $item->minor_color;
    $sale_date = $item->sale_date;
    $year = $item->year;
    $days = $item->days;
    $make = $item->make;
    $model = $item->model;
    $miles = $item->miles;
    $name_1 = $item->name_1;
    $name_2 = $item->name_2;
    $adress = $item->adress;
    $city = $item->city;
    $estado = $item->estado;
    $phone = $item->phone;
    $zip = $item->zip;
    $id_buyer = $item->id_buyer;

    $fecha =  $sale_date;
    if($fecha !== ''){
        $fecha_objeto = strtotime($fecha);
        $fecha_transformada = date("M d, Y", $fecha_objeto);
        $fecha_transformada_sale = date("m/d/Y", $fecha_objeto);
    }else{
        $fecha_transformada = '';
    }
    // echo $fecha_transformada;
    $sale_date = $fecha_objeto = strtotime($sale_date); // Suponiendo que $sale_date es la cadena de fecha
    $expires = date("m/d/Y", strtotime($fecha . " +$days days"));


$pdf = new FPDF();
$pdf->SetMargins(10,5,5);
$pdf->AddPage('P',array(280,216));
$pdf->SetAutoPageBreak(true,5); 
$pdf->SetFillColor(255,255,255);
$pdf->SetDrawColor(147,148,152);
$pdf->SetLineWidth(1);
$pdf->SetDrawColor(0,0,0);
$pdf->line(11,39,205,39);
$pdf->SetLineWidth(0.1);
$pdf->SetDash(1,1);
$pdf->line(11,46,198,46);
$pdf->SetLineWidth(0);
$pdf->SetDash(0,0);
$pdf->line(11,63,198,63);
$pdf->line(11,107,198,107);
$pdf->line(11,165,198,165);
$pdf->line(58.75,136,58.75,165);
$pdf->line(152,136,152,165);
$pdf->SetDash(1,1);
$pdf->line(11,238,198,238);
$pdf->line(11,46,11,238);
$pdf->line(198,46,198,238);
$pdf->line(104,46,104,238);

$pdf->AddFont('calibrib','','calibrib.php');
$pdf->AddFont('calibriz','','calibriz.php');
$pdf->AddFont('calibri','','calibril.php');
$pdf->AddFont('calibrili','','calibrili.php');
$pdf->AddFont('calibrin','','calibrin.php');
$pdf->AddFont('sans','','REFSAN.php');
$pdf->SetFont('calibriz','',14);
$pdf->Cell(1);
$pdf->Cell(260,6,"", 0, 1, 'C');
$pdf->SetTextColor(0,0,0);
$pdf->Cell(1);
$pdf->Cell(23,13,"", 0, 0, 'L');
$pdf->Cell(50,13,"Falcon Insurance Company", 0, 0, 'L');
$pdf->Image('Logo.jpg',15,14,18,19);
$pdf->SetFont('times','B',17);
$pdf->Cell(1);
$pdf->Cell(120,14,"Texas Liability Insurance Card", 0, 1, 'R');
$pdf->SetFont('calibriz','',8);
$pdf->Cell(1);
$pdf->Cell(23,-6,"", 0, 0, 'L');
$pdf->Cell(50,-6,"Serviced by Talon Financial Services, LLC", 0, 1, 'L');
$pdf->SetFont('calibrib','',10);
$pdf->Cell(1);
$pdf->Cell(23,14,"", 0, 0, 'L');
$pdf->Cell(50,14,"PO Box 3725", 0, 1, 'L');
$pdf->Cell(1);
$pdf->Cell(23,-4,"", 0, 0, 'L');
$pdf->Cell(50,-4,"Oak Brook, IL 60522  Phone 800-929-3252", 0, 1, 'L');
$pdf->Cell(1);
$pdf->Cell(150,22,"", 0, 1, 'L');
$pdf->SetFont('calibriz','',10);
$pdf->Cell(1);
$pdf->Cell(15,4,"", 0, 0, 'L');
$pdf->Cell(50,0,"Falcon Insurance Company", 0, 0, 'L');
$pdf->Image('Logo.jpg',14,49,11,11);
$pdf->Image('Logo.jpg',107,49,11,11);
$pdf->SetFont('calibriz','',11);
$pdf->Cell(23,-1,"TEXAS AUTO", 0, 0, 'C');
$pdf->Cell(21,4,"", 0, 0, 'L');
$pdf->SetFont('calibriz','',10);
$pdf->Cell(50,0,"Falcon Insurance Company", 0, 0, 'L');
$pdf->SetFont('calibriz','',11);
$pdf->Cell(22,-1,"TEXAS AUTO", 0, 1, 'C');
$pdf->SetFont('calibrib','',8.5);
$pdf->Cell(1);
$pdf->Cell(15,10,"", 0, 0, 'L');
$pdf->Cell(50,10,"PO Box 3725", 0, 0, 'L');
$pdf->SetFont('calibriz','',11);
$pdf->Cell(23,10,"INSURANCE CARD", 0, 0, 'C');
$pdf->Cell(21,10,"", 0, 0, 'L');
$pdf->SetFont('calibrib','',8.5);
$pdf->Cell(50,10,"PO Box 3725", 0, 0, 'L');
$pdf->SetFont('calibriz','',11);
$pdf->Cell(22,10,"INSURANCE CARD", 0, 1, 'C');
$pdf->SetFont('calibriz','',8.5);
$pdf->Cell(1);
$pdf->Cell(15,-2,"", 0, 0, 'L');
$pdf->Cell(50,-2,"Oak Brook, IL 60522", 0, 0, 'L');
$pdf->SetFont('calibriz','',11);
$pdf->Cell(23,-1,"NAIC# 25834", 0, 0, 'C');
$pdf->Cell(21,-2,"", 0, 0, 'L');
$pdf->SetFont('calibriz','',8.5);
$pdf->Cell(50,-2,"Oak Brook, IL 60522", 0, 0, 'L');
$pdf->SetFont('calibriz','',11);
$pdf->Cell(22,-1,"NAIC# 25834", 0, 1, 'C');
$pdf->SetFont('calibrib','',9);
$pdf->Cell(1);
$pdf->Cell(260,5,"", 0, 1, 'L');
$pdf->Cell(1);
$pdf->Cell(2,3,"", 0, 0, 'L');
$pdf->Cell(91,3,"lnsured Name", 0, 0, 'L');
$pdf->Cell(2,3,"", 0, 0, 'L');
$pdf->Cell(91,3,"Nombre del Asegurado", 0, 1, 'L');
$pdf->Cell(1);
$pdf->SetFont('sans','',7.5);
$pdf->Cell(2,3,"", 0, 0, 'L');
$pdf->Cell(41,5,utf8_decode("$name_1 $name_2"), 0, 0, 'L');
$pdf->SetFont('calibrib','',10);
$pdf->Cell(50,0,"Agency", 0, 0, 'C');
$pdf->Cell(2,3,"", 0, 0, 'L');
$pdf->SetFont('sans','',7.5);
$pdf->Cell(41,5,utf8_decode("$name_1 $name_2"), 0, 0, 'L');
$pdf->SetFont('calibrib','',10);
$pdf->Cell(50,0,"Agencia", 0, 1, 'C');
$pdf->Cell(1);
$pdf->SetFont('sans','',7.5);
$pdf->Cell(2,12,"", 0, 0, 'L');
$pdf->Cell(41,12,strtoupper("$adress"), 0, 0, 'L');
$pdf->SetFont('calibrin','',8);
$pdf->Cell(50,12,"Insurance Zebra, Inc", 0, 0, 'C');
$pdf->SetFont('sans','',7.5);
$pdf->Cell(2,12,"", 0, 0, 'L');
$pdf->Cell(41,12,strtoupper("$adress"), 0, 0, 'L');
$pdf->SetFont('calibrin','',8);
$pdf->Cell(50,12,"Insurance Zebra, Inc", 0, 1, 'C');
$pdf->Cell(1);
$pdf->SetFont('sans','',7.5);
$pdf->Cell(2,12,"", 0, 0, 'L');
$pdf->Cell(91,-5,strtoupper("$city, $estado"), 0, 0, 'L');
$pdf->Cell(2,-5,"", 0, 0, 'L');
$pdf->Cell(91,-5,strtoupper("$city, $estado"), 0, 1, 'L');
$pdf->Cell(1);
$pdf->SetFont('sans','',7);
$pdf->Cell(2,12,"", 0, 0, 'L');
$pdf->Cell(41,12,"$zip", 0, 0, 'L');
$pdf->SetFont('calibrin','',7);
$pdf->Cell(50,12,"(888)444-8949", 0, 0, 'C');
$pdf->SetFont('sans','',7);
$pdf->Cell(2,12,"", 0, 0, 'L');
$pdf->Cell(41,12,"$zip", 0, 0, 'L');
$pdf->SetFont('calibrin','',7);
$pdf->Cell(50,12,"(888)444-8949", 0, 1, 'C');
$pdf->Cell(1);
$pdf->SetFont('calibrib','',9);
$pdf->Cell(2,0,"", 0, 0, 'L');
$pdf->Cell(31,-1,"Policy Number", 0, 0, 'L');
$pdf->Cell(32,-3,"Effective Date", 0, 0, 'L');
$pdf->Cell(27,-3,"Expiration Date", 0, 0, 'L');
$pdf->Cell(1);
$pdf->SetFont('calibrib','',9);
$pdf->Cell(2,0,"", 0, 0, 'L');
$pdf->Cell(31,-1,"Policy Number", 0, 0, 'L');
$pdf->Cell(32,-3,"Effective Date", 0, 0, 'L');
$pdf->Cell(27,-3,"Expiration Date", 0, 1, 'L');
$pdf->Cell(1);
$pdf->SetFont('calibrib','',9);
$pdf->Cell(2,12,"", 0, 0, 'L');
$pdf->Cell(31,12,utf8_decode("Numero de Póliza"), 0, 0, 'L');
$pdf->Cell(29,9,"Fecha Efectiva", 0, 0, 'L');
$pdf->Cell(27,9,utf8_decode("Fecha de Expiración"), 0, 0, 'L');
$pdf->Cell(1);
$pdf->SetFont('calibrib','',9);
$pdf->Cell(4,12,"", 0, 0, 'L');
$pdf->Cell(31,12,utf8_decode("Numero de Póliza"), 0, 0, 'L');
$pdf->Cell(29,9,"Fecha Efectiva", 0, 0, 'L');
$pdf->Cell(27,9,utf8_decode("Fecha de Expiración"), 0, 1, 'L');
$pdf->Cell(1);
$pdf->SetFont('calibrin','',9);
$pdf->Cell(2,2,"", 0, 0, 'L');
$pdf->Cell(27,2,"9706351276-1", 0, 0, 'L');
date_default_timezone_set('America/New_York'); // Establece la zona horaria a Nueva York
$hora_actual = date("h:i A");
$pdf->Cell(31,0,"$fecha_transformada_sale $hora_actual", 0, 0, 'L');
$pdf->Cell(31,0,"$expires $hora_actual", 0, 0, 'L');
$pdf->Cell(1);
$pdf->SetFont('calibrin','',9);
$pdf->Cell(2,2,"", 0, 0, 'L');
$pdf->Cell(27,2,"9706351276-1", 0, 0, 'L');
$pdf->Cell(31,0,"$fecha_transformada_sale $hora_actual", 0, 0, 'L');
$pdf->Cell(33,0,"$expires $hora_actual", 0, 1, 'L');
$pdf->Cell(1);
$pdf->SetFont('calibrib','',9);
$pdf->Cell(20,10,"", 0, 0, 'L');
$pdf->Cell(71,10,"Year/Make/Model", 0, 0, 'L');
$pdf->Cell(20,10,"", 0, 0, 'L');
$pdf->Cell(71,10,"Year/Make/Model", 0, 1, 'L');
$pdf->Cell(1);
$pdf->SetFont('calibrib','',9);
$pdf->Cell(62,-3,utf8_decode("Año del Vehículo/Marca/Modelo"), 0, 0, 'C');
$pdf->Cell(26,-4,"VIN", 0, 0, 'C');
$pdf->Cell(4,-2,"", 0, 0, 'L');
$pdf->Cell(62,-3,utf8_decode("Año del Vehículo/Marca/Modelo"), 0, 0, 'C');
$pdf->Cell(26,-4,"VIN", 0, 1, 'C');
$pdf->Cell(1);
$pdf->SetFont('calibrin','',10);
$pdf->Cell(60,12,strtoupper("$year $make $model $body_style"), 0, 0, 'C');
$pdf->Cell(26,10,"$vin_vehicle", 0, 0, 'C');
$pdf->Cell(6,12,"", 0, 0, 'C');
$pdf->Cell(60,12,strtoupper("$year $make $model $body_style"), 0, 0, 'C');
$pdf->Cell(26,10,"$vin_vehicle", 0, 1, 'C');
$pdf->Cell(1);
$pdf->SetFont('calibriz','',10);
$pdf->Cell(1,8,"", 0, 0, 'L');
$pdf->Cell(91,8,"This policy provides at least the minimum amounts of liability", 0, 0, 'J');
$pdf->SetFont('calibriz','',9.3);
$pdf->Cell(2,8,"", 0, 0, 'L');
$pdf->Cell(91,8,utf8_decode("Esta póliza provee por lo menos la cantidad mínima de seguro de"), 0, 1, 'J');
$pdf->Cell(1);
$pdf->SetFont('calibriz','',9.1);
$pdf->Cell(1,1,"", 0, 0, 'L');
$pdf->Cell(91,1,"insurance required by the Texas Motor Vehicle Safety Responsibility", 0, 0, 'J');
$pdf->SetFont('calibriz','',9.3);
$pdf->Cell(2,1,"", 0, 0, 'L');
$pdf->Cell(91,1,utf8_decode("responsabilidad requerida por ley (Texas Motor Vehicle Safety"), 0, 1, 'J');
$pdf->Cell(1);
$pdf->SetFont('calibriz','',9.5);
$pdf->Cell(1,8,"", 0, 0, 'L');
$pdf->Cell(91,8,"Act for the specified vehicle and named insured and may provide", 0, 0, 'J');
$pdf->SetFont('calibriz','',9.5);
$pdf->Cell(2,8,"", 0, 0, 'L');
$pdf->Cell(91,8,utf8_decode("Responsibility Act) para el vehículo especificado y para los"), 0, 1, 'J');
$pdf->Cell(1);
$pdf->SetFont('calibriz','',9.5);
$pdf->Cell(1,1,"", 0, 0, 'L');
$pdf->Cell(91,1,"coverage for other persons and other vehicles as provided by the", 0, 0, 'J');
$pdf->SetFont('calibriz','',9.3);
$pdf->Cell(2,1,"", 0, 0, 'L');
$pdf->Cell(91,1,utf8_decode("asegurados mencionados, puede proveer cobertura para otras"), 0, 1, 'J');
$pdf->Cell(1);
$pdf->SetFont('calibriz','',9.5);
$pdf->Cell(1,8,"", 0, 0, 'L');
$pdf->Cell(91,8,"insurance policy.", 0, 0, 'J');
$pdf->SetFont('calibriz','',9.3);
$pdf->Cell(2,8,"", 0, 0, 'L');
$pdf->Cell(91,8,utf8_decode("personas y vehículos según sea previsto en la póliza de seguro."), 0, 1, 'J');
$pdf->Cell(1);
$pdf->SetFont('calibriz','',9.5);
$pdf->Cell(1,7,"", 0, 0, 'L');
$pdf->Cell(92,7,"The drivers on this policy:", 0, 0, 'L');
$pdf->Cell(1,7,"", 0, 0, 'L');
$pdf->Cell(91,7,utf8_decode("Los conductores de esta pólíza:"), 0, 1, 'L');
$pdf->Cell(1);
$pdf->SetFont('calibrin','',8.8);
$pdf->Cell(1,1,"", 0, 0, 'L');
$pdf->Cell(48,1,utf8_decode("$name_1 $name_2"), 0, 0, 'L');
$pdf->SetFont('calibrib','',9.2);
$pdf->Cell(1,2,"", 0, 0, 'L');
$pdf->Cell(43,-6,"Excluded from Coverage:", 0, 0, 'L');
$pdf->SetFont('calibrin','',8.8);
$pdf->Cell(1,1,"", 0, 0, 'L');
$pdf->Cell(48,1,utf8_decode("$name_1 $name_2"), 0, 0, 'L');
$pdf->SetFont('calibrib','',9.2);
$pdf->Cell(1,2,"", 0, 0, 'L');
$pdf->Cell(43,-6,"Excluidos de la cobertura:", 0, 1, 'L');

$pdf->Cell(1);
$pdf->Cell(93,31,"", 0, 1, 'L');
$pdf->SetFont('times','B',9);
$pdf->Cell(1);
$pdf->Cell(93,4,"Texas Liability Insurance Card", 0, 0, 'C');
$pdf->SetFont('calibriz','',9);
$pdf->Cell(93,4,"Tarjeta de Seguro de Responsabilidad de Texas", 0, 1, 'C');
$pdf->Cell(1);
$pdf->Cell(93,2,"", 0, 1, 'L');
$pdf->SetFont('times','B',9);
$pdf->Cell(1);
$pdf->Cell(93,2,"Keep this card", 0, 0, 'C');
$pdf->SetFont('calibriz','',9);
$pdf->Cell(93,2,"Guarde esta tarjeta", 0, 1, 'C');
$pdf->Cell(1);
$pdf->Cell(93,3,"", 0, 1, 'L');
$pdf->SetFont('times','B',9);
$pdf->Cell(1);
$pdf->Cell(1,1,"", 0, 0, 'L');
$pdf->Cell(16,3,"Important:", 0, 0, 'L');
$pdf->SetFont('calibrin','',8.7);
$pdf->Cell(77,3,"This card or a copy of your insurance policy must be shown", 0, 0, 'J');
$pdf->SetFont('times','B',9);
$pdf->Cell(18,3,"Importante:", 0, 0, 'L');
$pdf->SetFont('calibrin','',8.5);
$pdf->Cell(77,3,utf8_decode("Esta tarjeta o una copia de su póliza de seguro debe ser"), 0, 1, 'J');
$pdf->Cell(1);
$pdf->Cell(93,1.5,"", 0, 1, 'L');
$pdf->Cell(1);
$pdf->SetFont('calibrin','',8.5);
$pdf->Cell(1,1,"", 0, 0, 'L');
$pdf->Cell(93,1.5,"when you apply for or renew your:", 0, 0, 'J');
$pdf->SetFont('calibrin','',8.5);
$pdf->Cell(93,1.5,"mostrada cuando usted solicite o renueve su:", 0, 1, 'J');
$pdf->Cell(1);
$pdf->Cell(93,1.5,"", 0, 1, 'L');
$pdf->Cell(1);
$pdf->Cell(7,4,"", 0, 0, 'L');
$pdf->Cell(6,4,chr(149), 0, 0, 'L');
$pdf->Cell(80,4,"Motor vehicle registration", 0, 0, 'L');
$pdf->Cell(7,4,"", 0, 0, 'L');
$pdf->Cell(6,4,chr(149), 0, 0, 'L');
$pdf->Cell(80,4,utf8_decode("Registro de vehículo de motor"), 0, 1, 'L');
$pdf->Cell(1);
$pdf->Cell(7,4,"", 0, 0, 'L');
$pdf->Cell(6,4,chr(149), 0, 0, 'L');
$pdf->Cell(80,4,"Driver's license", 0, 0, 'L');
$pdf->Cell(7,4,"", 0, 0, 'L');
$pdf->Cell(6,4,chr(149), 0, 0, 'L');
$pdf->Cell(80,4,"Licencia de conducir", 0, 1, 'L');
$pdf->Cell(1);
$pdf->Cell(7,4,"", 0, 0, 'L');
$pdf->Cell(6,4,chr(149), 0, 0, 'L');
$pdf->Cell(80,4,"Motor vehicle safety inspection sticker", 0, 0, 'L');
$pdf->Cell(7,4,"", 0, 0, 'L');
$pdf->Cell(6,4,chr(149), 0, 0, 'L');
$pdf->Cell(80,4,utf8_decode("Etiqueta de inspección de seguridad de su vehículo"), 0, 1, 'L');
$pdf->Cell(1);
$pdf->Cell(7,1,"", 0, 1, 'L');
$pdf->Cell(1);
$pdf->SetFont('calibrin','',8.5);
$pdf->Cell(1,4,"", 0, 0, 'j');
$pdf->Cell(93,4,"You also may be asked to show this card or your policy if you have an", 0, 0, 'J');
$pdf->SetFont('calibrin','',8.5);
$pdf->Cell(93,4,utf8_decode("Puede que usted tenga también que mostrar esta tarjeta o su póliza de"), 0, 1, 'J');
$pdf->Cell(1);
$pdf->SetFont('calibrin','',8.5);
$pdf->Cell(1,4,"", 0, 0, 'j');
$pdf->Cell(93,4,"accident or if a peace officer asks to see it.", 0, 0, 'J');
$pdf->SetFont('calibrin','',8.5);
$pdf->Cell(93,4,utf8_decode("seguro si tiene un accidente o si un o/icial de la paz se la pide."), 0, 1, 'J');
$pdf->Cell(1);
$pdf->SetFont('calibrin','',8.5);
$pdf->Cell(1,5,"", 0, 0, 'j');
$pdf->Cell(93,5,"All drivers in Texas must carry liability insurance on their vehicles or", 0, 0, 'J');
$pdf->SetFont('calibrin','',8.2);
$pdf->Cell(93,5,utf8_decode("Todos los conductores en Texas deben de tener seguro de responsabilidad"), 0, 1, 'J');
$pdf->Cell(1);
$pdf->SetFont('calibrin','',8.2);
$pdf->Cell(1,3,"", 0, 0, 'j');
$pdf->Cell(93,3,"otherwise meet legal requirements for financial responsibility. Failure to", 0, 0, 'J');
$pdf->SetFont('calibrin','',8.2);
$pdf->Cell(93,3,utf8_decode("para sus vehículos, o de otra manera satis/acer los requisitos legales de la"), 0, 1, 'J');
$pdf->Cell(1);
$pdf->SetFont('calibrin','',8.2);
$pdf->Cell(1,4,"", 0, 0, 'j');
$pdf->Cell(93,4,"do so could result in fines up to $1,000, suspension of your driver's", 0, 0, 'J');
$pdf->SetFont('calibrin','',8.2);
$pdf->Cell(93,4,utf8_decode("responsabilidad /inanciera. Falta de cumplir con este requisito pudiera"), 0, 1, 'J');
$pdf->Cell(1);
$pdf->SetFont('calibrin','',8.2);
$pdf->Cell(1,3,"", 0, 0, 'j');
$pdf->Cell(93,3,"license and motor vehicle registration, and impoundment of your vehicle", 0, 0, 'J');
$pdf->SetFont('calibrin','',8.2);
$pdf->Cell(93,3,utf8_decode("resultar en multas de hasta $1,000, suspensión de su licencia de conducir"), 0, 1, 'J');
$pdf->Cell(1);
$pdf->SetFont('calibrin','',8.2);
$pdf->Cell(1,4,"", 0, 0, 'j');
$pdf->Cell(93,4,"for up to 180 days (at a cost of $15 per day).", 0, 0, 'J');
$pdf->SetFont('calibrin','',8.2);
$pdf->Cell(93,4,utf8_decode("y del registro de su vehículo de motor, y la retención de su vehículo por un"), 0, 1, 'J');
$pdf->Cell(1);
$pdf->SetFont('calibrin','',8.2);
$pdf->Cell(1,3,"", 0, 0, 'j');
$pdf->Cell(93,3,"", 0, 0, 'J');
$pdf->SetFont('calibrin','',8.2);
$pdf->Cell(93,3,utf8_decode("periodo de hasta 180 días (a un costo de $15 por día)."), 0, 1, 'J');
$pdf->Cell(1);
$pdf->SetFont('calibrin','',8.2);
$pdf->Cell(1,2,"", 0, 0, 'j');
$pdf->Cell(93,2,"Call our service center toll free at (800) 929-3252 to notify a claim.", 0, 0, 'J');
$pdf->SetFont('calibrin','',8.2);
$pdf->Cell(93,2,"", 0, 1, 'J');
$pdf->Cell(1);
$pdf->SetFont('calibrin','',8.2);
$pdf->Cell(1,4,"", 0, 0, 'j');
$pdf->Cell(93,4,"", 0, 0, 'J');
$pdf->SetFont('calibrin','',8.2);
$pdf->Cell(93,4,utf8_decode("Notifíque su accidente llamando gratis  al centro de servicio (800) 929-3252"), 0, 1, 'J');
$pdf->Cell(1);
$pdf->Cell(100,12,"", 0, 1, 'j');
$pdf->Cell(1);
$pdf->SetFont('calibrib','',10);
$pdf->Cell(192,5,"If you lose your card, contact your Falcon agent.", 0, 1, 'C');

$numeroAleatorio = mt_rand(10, 99);
// $pdf->Output();
$filenamepdf="TAG-Insurance-$numeroAleatorio.pdf";
// Definir el tipo de contenido y configurar el encabezado Content-Disposition
header('Content-Type: application/pdf');
header("Content-Disposition: inline; filename=$filenamepdf");


$pdf->Output($filenamepdf,'I');

echo "<script>
         window.location.href = $filenamepdf;
     </script>";


    }
?>
